CREATE TABLE [menu] (
  [Item] TEXT,
  [Category] TEXT,
  [Subcategory] TEXT NULL,
  [Price] REAL,
  [Option] TEXT NULL
);

INSERT INTO [menu] ([Item],[Category],[Subcategory],[Price],[Option])
VALUES
('Bagel with Either Cream Cheese or Butter','Breakfast','Breakfast Sandwiches',2.99,NULL),
('Egg & Cheese Breakfast Sandwich','Breakfast','Breakfast Sandwiches',3.49,NULL),
('Meat, Egg & Cheese Breakfast Sandwich','Breakfast','Breakfast Sandwiches',5.99,NULL),
('Grilled Cheese Meat, Egg & Cheese','Breakfast','Breakfast Sandwiches',7.99,NULL),
('French Toast Meat, Egg & Cheese','Breakfast','Breakfast Sandwiches',7.99,'Yes'),
('Breakfast Burrito','Breakfast','Breakfast Sandwiches',8.99,'Yes'),
('Egg & Cheese Breakfast Platter','Breakfast','Breakfast Platters',6.49,NULL),
('Meat, Egg & Cheese Breakfast Platter','Breakfast','Breakfast Platters',8.99,NULL),
('Cheese Omelette','Breakfast','Breakfast Platters',6.99,NULL),
('Western Omelette','Breakfast','Breakfast Platters',9.99,'Yes'),
('Veggie Omelette','Breakfast','Breakfast Platters',8.99,'Yes'),
('Halal Meat Lovers Omelette','Breakfast','Breakfast Platters',10.99,'Yes'),
('Philly Cheesesteak Omelette','Breakfast','Breakfast Platters',10.99,'Yes'),
('Small Grits','Breakfast','Breakfast Sides',2.99,NULL),
('Large Grits','Breakfast','Breakfast Sides',3.99,NULL),
('Home Fries','Breakfast','Breakfast Sides',3.49,NULL),
('Short Stack Pancakes','Breakfast','Breakfast Sides',4.99,NULL),
('Pancakes','Breakfast','Breakfast Sides',6.99,NULL),
('French Toast ','Breakfast','Breakfast Sides',6.99,NULL),
('Side of Pork Bacon','Breakfast','Breakfast Sides',2.99,NULL),
('Side of Turkey Bacon 3pc','Breakfast','Breakfast Sides',2.99,NULL),
('Side of Beef Sausage 1pc','Breakfast','Breakfast Sides',2.99,NULL),
('Side of Beef Bacon','Breakfast','Breakfast Sides',2.99,NULL),
('Fries','Appetizers',NULL,2.99,NULL),
('Cheese Fries','Appetizers',NULL,4.49,NULL),
('Tater Tots','Appetizers',NULL,3.99,NULL),
('Cheesy Tater Tots','Appetizers',NULL,5.49,NULL),
('Curly Fries','Appetizers',NULL,3.99,NULL),
('Onion Rings','Appetizers',NULL,3.99,NULL),
('Sweet Potato Fries','Appetizers',NULL,3.99,NULL),
('Mozzarella Sticks 6pc','Appetizers',NULL,5.99,NULL),
('Animal Style Fries','Specialty Fries ',NULL,4.99,'Yes'),
('Pizza Fries','Specialty Fries ',NULL,9.99,'Yes'),
('Cheesesteak Fries','Specialty Fries ',NULL,9.99,'Yes'),
('Thai Chili Cheddar Fries','Specialty Fries ',NULL,9.99,'Yes'),
('Nashville Hot Tender Fries','Specialty Fries ',NULL,9.99,'Yes'),
('Chopped Cheeseburger Fries','Specialty Fries ',NULL,9.99,'Yes'),
('Turkey','Cold Sandwiches',NULL,6.99,NULL),
('Tuna','Cold Sandwiches',NULL,6.99,NULL),
('Turkey Ham','Cold Sandwiches',NULL,6.99,NULL),
('Ham','Cold Sandwiches',NULL,6.99,NULL),
('Italian','Cold Sandwiches',NULL,7.49,NULL),
('Cheese','Cold Sandwiches',NULL,4.99,NULL),
('Corned Beef','Cold Sandwiches',NULL,7.99,NULL),
('Pastrami','Cold Sandwiches',NULL,7.99,NULL),
('Roast Beef','Cold Sandwiches',NULL,7.99,NULL),
('Halal Italian','Cold Sandwiches',NULL,8.49,NULL),
('Corned Beef Special','Cold Sandwiches',NULL,8.49,'Yes'),
('Our Famous Beef Sausage','Hot Sandwiches',NULL,3.49,'Yes'),
('Meatball Parm Sub','Hot Sandwiches',NULL,9.99,'Yes'),
('Tuna Melt','Hot Sandwiches',NULL,7.99,NULL),
('BLT','Hot Sandwiches',NULL,6.99,NULL),
('Turkey Club','Hot Sandwiches',NULL,8.99,NULL),
('Hot Pastrami','Hot Sandwiches',NULL,8.49,NULL),
('Hot Roast Beef','Hot Sandwiches',NULL,8.49,NULL),
('Hot Corned Beef','Hot Sandwiches',NULL,8.49,NULL),
('Hot Turkey','Hot Sandwiches',NULL,7.49,NULL),
('Corned Beef Reuben','Hot Sandwiches',NULL,8.99,'Yes'),
('Cedar Reuben','Hot Sandwiches',NULL,9.99,'Yes'),
('Cheesesteak ','Steaks',NULL,9.99,NULL),
('Chicken Steak','Steaks',NULL,9.99,NULL),
('Cedar Double Steak','Steaks',NULL,12.99,'Yes'),
('Philly Cheesesteak  ','Steaks',NULL,10.99,'Yes'),
('Pizza Cheesesteak','Steaks',NULL,11.99,'Yes'),
('Bacon Cheesesteak','Steaks',NULL,11.99,'Yes'),
('Mushroom Swiss Cheesesteak','Steaks',NULL,10.99,'Yes'),
('California Chicken Cheesteak','Steaks',NULL,10.49,'Yes'),
('Buffalo Chicken Cheesesteak','Steaks',NULL,10.99,'Yes'),
('Sweet & Spicy Chicken Cheesesteak','Steaks',NULL,10.99,'Yes'),
('Burger','Burgers',NULL,6.99,NULL),
('Bacon Burger','Burgers',NULL,8.99,NULL),
('NYC Chopped Cheese','Burgers',NULL,10.99,'Yes'),
('Cedar Turkey Burger','Burgers',NULL,8.99,'Yes'),
('Gyro Burger','Burgers',NULL,8.99,'Yes'),
('Western Burger','Burgers',NULL,8.99,'Yes'),
('Mushroom Swiss Burger','Burgers',NULL,7.49,'Yes'),
('California Burger','Burgers',NULL,7.49,'Yes'),
('Burger Patty Melt','Burgers',NULL,7.99,'Yes'),
('Cedar Brunch Burger','Burgers',NULL,9.99,'Yes'),
('Cedar Quesadilla','Quesadillas',NULL,10.99,'Yes'),
('Thai Chili Quesadilla','Quesadillas',NULL,10.99,'Yes'),
('Philly Quesadilla','Quesadillas',NULL,10.99,'Yes'),
('Do Cedar','Do AC Sandwiches',NULL,10.99,'Yes'),
('Do Borgata','Do AC Sandwiches',NULL,10.99,'Yes'),
('Do Harrahs','Do AC Sandwiches',NULL,10.99,'Yes'),
('Do Hard Rock','Do AC Sandwiches',NULL,10.99,'Yes'),
('Do Tropicana','Do AC Sandwiches',NULL,10.99,'Yes'),
('Do Caesars','Do AC Sandwiches',NULL,10.99,'Yes'),
('Do Golden Nugget','Do AC Sandwiches',NULL,10.99,'Yes'),
('Do Resorts','Do AC Sandwiches',NULL,10.99,'Yes'),
('Cheese Pizza','Pizza',NULL,13.99,'Yes'),
('Build Your Own Pizza','Pizza',NULL,13.99,'Yes'),
('Veggie Pizza','Pizza',NULL,15.99,'Yes'),
('Thai Chili Pizza','Pizza',NULL,17.99,'Yes'),
('Taco Pizza','Pizza',NULL,17.99,'Yes'),
('Buffalo Chicken Pizza','Pizza',NULL,17.99,'Yes'),
('Chicken Turkey Bacon Ranch','Pizza',NULL,18.99,'Yes'),
('CheeseSteak Pizza','Pizza',NULL,17.99,'Yes'),
('Bbq Chicken Pizza','Pizza',NULL,17.99,'Yes'),
('White Pizza','Pizza',NULL,16.99,'Yes'),
('Halal Meat Lovers','Pizza',NULL,19.99,'Yes'),
('Classic Grilled Cheese','Grilled Cheese',NULL,4.49,'Yes'),
('Thai Chili Chicken Grilled Cheese','Grilled Cheese',NULL,7.49,'Yes'),
('Bacon Grilled Cheese','Grilled Cheese',NULL,7.49,'Yes'),
('Triple Cheese Grilled Cheese','Grilled Cheese',NULL,5.49,'Yes'),
('Whiting Sandwich','Seafood',NULL,6.99,'Yes'),
('Cedar Fish Sandwich','Seafood',NULL,7.99,'Yes'),
('Six Piece Jumbo Shrimp','Seafood',NULL,5.99,'Yes'),
('Popcorn Shrimp','Seafood',NULL,5.99,'Yes'),
('Seafood Platter','Seafood',NULL,12.99,NULL),
('Gyro Wrap','Wraps',NULL,9.99,'Yes'),
('Chicken Caesar','Wraps',NULL,9.99,'Yes'),
('Buffalo Chicken','Wraps',NULL,8.99,'Yes'),
('Vegetable Wrap','Wraps',NULL,8.99,'Yes'),
('Cedar Chicken Wrap','Wraps',NULL,9.99,'Yes'),
('4 Pc Wings','Chicken',NULL,3.99,'Yes'),
('6 Pc Wings','Chicken',NULL,5.99,'Yes'),
('12 Pc Wings','Chicken',NULL,10.99,'Yes'),
('24 Pc Wings','Chicken',NULL,21.99,'Yes'),
('50 Pc Wings','Chicken',NULL,42.99,'Yes'),
('100 Pc Wings','Chicken',NULL,84.99,'Yes'),
('4 Pc Tenders','Chicken',NULL,5.99,'Yes'),
('6 Pc Tenders','Chicken',NULL,8.99,'Yes'),
('12 Pc Tenders','Chicken',NULL,16.99,'Yes'),
('24 Pc Tenders','Chicken',NULL,30.99,'Yes'),
('50 Pc Tenders','Chicken',NULL,62.99,'Yes'),
('100 Pc Tenders','Chicken',NULL,119.99,'Yes'),
('Fried Chicken Sandwich','Chicken Sandwich',NULL,6.99,'Yes'),
('Grilled Chicken Sandwich','Chicken Sandwich',NULL,6.99,'Yes'),
('Chicken Parm','Chicken Sandwich',NULL,7.49,'Yes'),
('Nashville Hot Chicken Sandwich','Chicken Sandwich',NULL,7.99,'Yes'),
('Hot Honey Fried Chicken Sandwich','Chicken Sandwich',NULL,7.99,'Yes'),
('Cedar Fried Chicken Sandwich','Chicken Sandwich',NULL,8.99,'Yes'),
('Garden Salad','Freshly Made Salads',NULL,3.99,'Yes'),
('Tuna Salad','Freshly Made Salads',NULL,6.99,'Yes'),
('Turkey Salad','Freshly Made Salads',NULL,6.99,'Yes'),
('Italian Salad','Freshly Made Salads',NULL,6.99,'Yes'),
('Halal Italian salad','Freshly Made Salads',NULL,7.99,'Yes'),
('Fried Chicken Caesar Salad','Freshly Made Salads',NULL,7.99,'Yes'),
('Grilled Chicken Caesar Salad','Freshly Made Salads',NULL,7.99,'Yes'),
('Fried Chicken Salad','Freshly Made Salads',NULL,7.99,'Yes'),
('Grilled Chicken Salad','Freshly Made Salads',NULL,7.99,'Yes'),
('Combo Chef Salad Turkey & Tuna','Freshly Made Salads',NULL,8.99,'Yes'),
('Combo Chef Salad Italian Meats & Tuna','Freshly Made Salads',NULL,8.99,'Yes');
