BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Food" (
	"FoodID"	INTEGER NOT NULL,
	"Name"	VARCHAR(100) NOT NULL,
	"Price"	FLOAT NOT NULL,
	"Category"	VARCHAR(100) NOT NULL,
	"Image"	BLOB,
	PRIMARY KEY("FoodID")
);
INSERT INTO "Food" VALUES (1,'Bagel with Either Cream Cheese or Butter',2.99,'Breakfast','static\Food Pictures\1 Bagel Cream Cheese.jpg');
INSERT INTO "Food" VALUES (2,'Egg & Cheese Breakfast Sandwich',3.49,'Breakfast','static\Food Pictures\2 Egg and cheese sandwich.jpg');
INSERT INTO "Food" VALUES (3,'Meat, Egg & Cheese Breakfast Sandwich',5.99,'Breakfast','static\Food Pictures\3 Bacon egg and cheese sandwich.jpg');
INSERT INTO "Food" VALUES (4,'Grilled Cheese Meat, Egg & Cheese',7.99,'Breakfast','static\Food Pictures\4 grilled cheese meat Egg and cheese.jpg');
INSERT INTO "Food" VALUES (5,'French Toast Meat, Egg & Cheese',7.99,'Breakfast','static\Food Pictures\5 french toast meat Egg and cheese.jpg');
INSERT INTO "Food" VALUES (6,'Breakfast Burrito',8.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (7,'Egg & Cheese Breakfast Platter',6.49,'Breakfast',NULL);
INSERT INTO "Food" VALUES (8,'Meat, Egg & Cheese Breakfast Platter',8.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (9,'Cheese Omelette',6.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (10,'Western Omelette',9.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (11,'Veggie Omelette',8.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (12,'Halal Meat Lovers Omelette',10.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (13,'Philly Cheesesteak Omelette',10.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (14,'Small Grits',2.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (15,'Large Grits',3.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (16,'Home Fries',3.49,'Breakfast',NULL);
INSERT INTO "Food" VALUES (17,'Short Stack Pancakes',4.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (18,'Pancakes',6.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (19,'French Toast ',6.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (20,'Side of Pork Bacon',2.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (21,'Side of Turkey Bacon 3pc',2.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (22,'Side of Beef Sausage 1pc',2.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (23,'Side of Beef Bacon',2.99,'Breakfast',NULL);
INSERT INTO "Food" VALUES (24,'Fries',2.99,'Appetizers',NULL);
INSERT INTO "Food" VALUES (25,'Cheese Fries',4.49,'Appetizers',NULL);
INSERT INTO "Food" VALUES (26,'Tater Tots',3.99,'Appetizers',NULL);
INSERT INTO "Food" VALUES (27,'Cheesy Tater Tots',5.49,'Appetizers',NULL);
INSERT INTO "Food" VALUES (28,'Curly Fries',3.99,'Appetizers',NULL);
INSERT INTO "Food" VALUES (29,'Onion Rings',3.99,'Appetizers',NULL);
INSERT INTO "Food" VALUES (30,'Sweet Potato Fries',3.99,'Appetizers',NULL);
INSERT INTO "Food" VALUES (31,'Mozzarella Sticks 6pc',5.99,'Appetizers',NULL);
INSERT INTO "Food" VALUES (32,'Animal Style Fries',4.99,'Specialty Fries ',NULL);
INSERT INTO "Food" VALUES (33,'Pizza Fries',9.99,'Specialty Fries ',NULL);
INSERT INTO "Food" VALUES (34,'Cheesesteak Fries',9.99,'Specialty Fries ',NULL);
INSERT INTO "Food" VALUES (35,'Thai Chili Cheddar Fries',9.99,'Specialty Fries ',NULL);
INSERT INTO "Food" VALUES (36,'Nashville Hot Tender Fries',9.99,'Specialty Fries ',NULL);
INSERT INTO "Food" VALUES (37,'Chopped Cheeseburger Fries',9.99,'Specialty Fries ',NULL);
INSERT INTO "Food" VALUES (38,'Turkey',6.99,'Cold Sandwiches',NULL);
INSERT INTO "Food" VALUES (39,'Tuna',6.99,'Cold Sandwiches',NULL);
INSERT INTO "Food" VALUES (40,'Turkey Ham',6.99,'Cold Sandwiches',NULL);
INSERT INTO "Food" VALUES (41,'Ham',6.99,'Cold Sandwiches',NULL);
INSERT INTO "Food" VALUES (42,'Italian',7.49,'Cold Sandwiches',NULL);
INSERT INTO "Food" VALUES (43,'Cheese',4.99,'Cold Sandwiches',NULL);
INSERT INTO "Food" VALUES (44,'Corned Beef',7.99,'Cold Sandwiches',NULL);
INSERT INTO "Food" VALUES (45,'Pastrami',7.99,'Cold Sandwiches',NULL);
INSERT INTO "Food" VALUES (46,'Roast Beef',7.99,'Cold Sandwiches',NULL);
INSERT INTO "Food" VALUES (47,'Halal Italian',8.49,'Cold Sandwiches',NULL);
INSERT INTO "Food" VALUES (48,'Corned Beef Special',8.49,'Cold Sandwiches',NULL);
INSERT INTO "Food" VALUES (49,'Our Famous Beef Sausage',3.49,'Hot Sandwiches',NULL);
INSERT INTO "Food" VALUES (50,'Meatball Parm Sub',9.99,'Hot Sandwiches',NULL);
INSERT INTO "Food" VALUES (51,'Tuna Melt',7.99,'Hot Sandwiches',NULL);
INSERT INTO "Food" VALUES (52,'BLT',6.99,'Hot Sandwiches',NULL);
INSERT INTO "Food" VALUES (53,'Turkey Club',8.99,'Hot Sandwiches',NULL);
INSERT INTO "Food" VALUES (54,'Hot Pastrami',8.49,'Hot Sandwiches',NULL);
INSERT INTO "Food" VALUES (55,'Hot Roast Beef',8.49,'Hot Sandwiches',NULL);
INSERT INTO "Food" VALUES (56,'Hot Corned Beef',8.49,'Hot Sandwiches',NULL);
INSERT INTO "Food" VALUES (57,'Hot Turkey',7.49,'Hot Sandwiches',NULL);
INSERT INTO "Food" VALUES (58,'Corned Beef Reuben',8.99,'Hot Sandwiches',NULL);
INSERT INTO "Food" VALUES (59,'Cedar Reuben',9.99,'Hot Sandwiches',NULL);
INSERT INTO "Food" VALUES (60,'Cheesesteak ',9.99,'Steaks',NULL);
INSERT INTO "Food" VALUES (61,'Chicken Steak',9.99,'Steaks',NULL);
INSERT INTO "Food" VALUES (62,'Cedar Double Steak',12.99,'Steaks',NULL);
INSERT INTO "Food" VALUES (63,'Philly Cheesesteak  ',10.99,'Steaks',NULL);
INSERT INTO "Food" VALUES (64,'Pizza Cheesesteak',11.99,'Steaks',NULL);
INSERT INTO "Food" VALUES (65,'Bacon Cheesesteak',11.99,'Steaks',NULL);
INSERT INTO "Food" VALUES (66,'Mushroom Swiss Cheesesteak',10.99,'Steaks',NULL);
INSERT INTO "Food" VALUES (67,'California Chicken Cheesteak',10.49,'Steaks',NULL);
INSERT INTO "Food" VALUES (68,'Buffalo Chicken Cheesesteak',10.99,'Steaks',NULL);
INSERT INTO "Food" VALUES (69,'Sweet & Spicy Chicken Cheesesteak',10.99,'Steaks',NULL);
INSERT INTO "Food" VALUES (70,'Burger',6.99,'Burgers',NULL);
INSERT INTO "Food" VALUES (71,'Bacon Burger',8.99,'Burgers',NULL);
INSERT INTO "Food" VALUES (72,'NYC Chopped Cheese',10.99,'Burgers',NULL);
INSERT INTO "Food" VALUES (73,'Cedar Turkey Burger',8.99,'Burgers',NULL);
INSERT INTO "Food" VALUES (74,'Gyro Burger',8.99,'Burgers',NULL);
INSERT INTO "Food" VALUES (75,'Western Burger',8.99,'Burgers',NULL);
INSERT INTO "Food" VALUES (76,'Mushroom Swiss Burger',7.49,'Burgers',NULL);
INSERT INTO "Food" VALUES (77,'California Burger',7.49,'Burgers',NULL);
INSERT INTO "Food" VALUES (78,'Burger Patty Melt',7.99,'Burgers',NULL);
INSERT INTO "Food" VALUES (79,'Cedar Brunch Burger',9.99,'Burgers',NULL);
INSERT INTO "Food" VALUES (80,'Cedar Quesadilla',10.99,'Quesadillas',NULL);
INSERT INTO "Food" VALUES (81,'Thai Chili Quesadilla',10.99,'Quesadillas',NULL);
INSERT INTO "Food" VALUES (82,'Philly Quesadilla',10.99,'Quesadillas',NULL);
INSERT INTO "Food" VALUES (83,'Do Cedar',10.99,'Do AC Sandwiches',NULL);
INSERT INTO "Food" VALUES (84,'Do Borgata',10.99,'Do AC Sandwiches',NULL);
INSERT INTO "Food" VALUES (85,'Do Harrahs',10.99,'Do AC Sandwiches',NULL);
INSERT INTO "Food" VALUES (86,'Do Hard Rock',10.99,'Do AC Sandwiches',NULL);
INSERT INTO "Food" VALUES (87,'Do Tropicana',10.99,'Do AC Sandwiches',NULL);
INSERT INTO "Food" VALUES (88,'Do Caesars',10.99,'Do AC Sandwiches',NULL);
INSERT INTO "Food" VALUES (89,'Do Golden Nugget',10.99,'Do AC Sandwiches',NULL);
INSERT INTO "Food" VALUES (90,'Do Resorts',10.99,'Do AC Sandwiches',NULL);
INSERT INTO "Food" VALUES (91,'Cheese Pizza',13.99,'Pizza',NULL);
INSERT INTO "Food" VALUES (92,'Build Your Own Pizza',13.99,'Pizza',NULL);
INSERT INTO "Food" VALUES (93,'Veggie Pizza',15.99,'Pizza',NULL);
INSERT INTO "Food" VALUES (94,'Thai Chili Pizza',17.99,'Pizza',NULL);
INSERT INTO "Food" VALUES (95,'Taco Pizza',17.99,'Pizza',NULL);
INSERT INTO "Food" VALUES (96,'Buffalo Chicken Pizza',17.99,'Pizza',NULL);
INSERT INTO "Food" VALUES (97,'Chicken Turkey Bacon Ranch',18.99,'Pizza',NULL);
INSERT INTO "Food" VALUES (98,'CheeseSteak Pizza',17.99,'Pizza',NULL);
INSERT INTO "Food" VALUES (99,'Bbq Chicken Pizza',17.99,'Pizza',NULL);
INSERT INTO "Food" VALUES (100,'White Pizza',16.99,'Pizza',NULL);
INSERT INTO "Food" VALUES (101,'Halal Meat Lovers',19.99,'Pizza',NULL);
INSERT INTO "Food" VALUES (102,'Classic Grilled Cheese',4.49,'Grilled Cheese',NULL);
INSERT INTO "Food" VALUES (103,'Thai Chili Chicken Grilled Cheese',7.49,'Grilled Cheese',NULL);
INSERT INTO "Food" VALUES (104,'Bacon Grilled Cheese',7.49,'Grilled Cheese',NULL);
INSERT INTO "Food" VALUES (105,'Triple Cheese Grilled Cheese',5.49,'Grilled Cheese',NULL);
INSERT INTO "Food" VALUES (106,'Whiting Sandwich',6.99,'Seafood',NULL);
INSERT INTO "Food" VALUES (107,'Cedar Fish Sandwich',7.99,'Seafood',NULL);
INSERT INTO "Food" VALUES (108,'Six Piece Jumbo Shrimp',5.99,'Seafood',NULL);
INSERT INTO "Food" VALUES (109,'Popcorn Shrimp',5.99,'Seafood',NULL);
INSERT INTO "Food" VALUES (110,'Seafood Platter',12.99,'Seafood',NULL);
INSERT INTO "Food" VALUES (111,'Gyro Wrap',9.99,'Wraps',NULL);
INSERT INTO "Food" VALUES (112,'Chicken Caesar',9.99,'Wraps',NULL);
INSERT INTO "Food" VALUES (113,'Buffalo Chicken',8.99,'Wraps',NULL);
INSERT INTO "Food" VALUES (114,'Vegetable Wrap',8.99,'Wraps',NULL);
INSERT INTO "Food" VALUES (115,'Cedar Chicken Wrap',9.99,'Wraps',NULL);
INSERT INTO "Food" VALUES (116,'4 Pc Wings',3.99,'Chicken',NULL);
INSERT INTO "Food" VALUES (117,'6 Pc Wings',5.99,'Chicken',NULL);
INSERT INTO "Food" VALUES (118,'12 Pc Wings',10.99,'Chicken',NULL);
INSERT INTO "Food" VALUES (119,'24 Pc Wings',21.99,'Chicken',NULL);
INSERT INTO "Food" VALUES (120,'50 Pc Wings',42.99,'Chicken',NULL);
INSERT INTO "Food" VALUES (121,'100 Pc Wings',84.99,'Chicken',NULL);
INSERT INTO "Food" VALUES (122,'4 Pc Tenders',5.99,'Chicken',NULL);
INSERT INTO "Food" VALUES (123,'6 Pc Tenders',8.99,'Chicken',NULL);
INSERT INTO "Food" VALUES (124,'12 Pc Tenders',16.99,'Chicken',NULL);
INSERT INTO "Food" VALUES (125,'24 Pc Tenders',30.99,'Chicken',NULL);
INSERT INTO "Food" VALUES (126,'50 Pc Tenders',62.99,'Chicken',NULL);
INSERT INTO "Food" VALUES (127,'100 Pc Tenders',119.99,'Chicken',NULL);
INSERT INTO "Food" VALUES (128,'Fried Chicken Sandwich',6.99,'Chicken Sandwich',NULL);
INSERT INTO "Food" VALUES (129,'Grilled Chicken Sandwich',6.99,'Chicken Sandwich',NULL);
INSERT INTO "Food" VALUES (130,'Chicken Parm',7.49,'Chicken Sandwich',NULL);
INSERT INTO "Food" VALUES (131,'Nashville Hot Chicken Sandwich',7.99,'Chicken Sandwich',NULL);
INSERT INTO "Food" VALUES (132,'Hot Honey Fried Chicken Sandwich',7.99,'Chicken Sandwich',NULL);
INSERT INTO "Food" VALUES (133,'Cedar Fried Chicken Sandwich',8.99,'Chicken Sandwich',NULL);
INSERT INTO "Food" VALUES (134,'Garden Salad',3.99,'Freshly Made Salads',NULL);
INSERT INTO "Food" VALUES (135,'Tuna Salad',6.99,'Freshly Made Salads',NULL);
INSERT INTO "Food" VALUES (136,'Turkey Salad',6.99,'Freshly Made Salads',NULL);
INSERT INTO "Food" VALUES (137,'Italian Salad',6.99,'Freshly Made Salads',NULL);
INSERT INTO "Food" VALUES (138,'Halal Italian salad',7.99,'Freshly Made Salads',NULL);
INSERT INTO "Food" VALUES (139,'Fried Chicken Caesar Salad',7.99,'Freshly Made Salads',NULL);
INSERT INTO "Food" VALUES (140,'Grilled Chicken Caesar Salad',7.99,'Freshly Made Salads',NULL);
INSERT INTO "Food" VALUES (141,'Fried Chicken Salad',7.99,'Freshly Made Salads',NULL);
INSERT INTO "Food" VALUES (142,'Grilled Chicken Salad',7.99,'Freshly Made Salads',NULL);
INSERT INTO "Food" VALUES (143,'Combo Chef Salad Turkey & Tuna',8.99,'Freshly Made Salads',NULL);
INSERT INTO "Food" VALUES (144,'Combo Chef Salad Italian Meats & Tuna',8.99,'Freshly Made Salads',NULL);
COMMIT;
